spring:
  datasource:
    url: jdbc:postgresql://103.97.125.92:5432/guno_db_test?useSSL=false
    username: guno_user
    password: UYUgjL80moKrc6WTDLbg
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  quartz:
    job-store-type: memory

meta:
  ads:
    app-id: ${META_APP_ID}
    app-secret: ${META_APP_SECRET}
    access-token: ${META_ACCESS_TOKEN}
    business-id: ${META_BUSINESS_ID}
    api-version: ${META_API_VERSION:v19.0}
    base-url: ${META_BASE_URL:https://graph.facebook.com}
    rate-limit:
      requests-per-hour: 50
      retry-attempts: 3
      retry-delay-ms: 5000

scheduler:
  enabled: false

batch:
  size: 100
  processing:
    chunk-size: 50
    thread-pool-size: 2

logging:
  level:
    com.gunads: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.test: DEBUG
  file:
    name: logs/guna-ads-test.log