spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 20000
      leak-detection-threshold: 60000

meta:
  ads:
    rate-limit:
      requests-per-hour: 200
      retry-attempts: 5
      retry-delay-ms: 10000

scheduler:
  enabled: true

batch:
  size: 5000
  processing:
    chunk-size: 1000
    thread-pool-size: 10

logging:
  level:
    com.gunads: INFO
    org.springframework.jdbc: WARN
    com.facebook.ads: ERROR
  file:
    name: logs/guna-ads-prod.log
    max-file-size: 100MB
    max-history: 30
    total-size-cap: 3GB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always